unit Languages;

interface

uses
  Windows;

  // languages data
  procedure Deutsch;
  procedure Englisch;
  procedure Italiano;
  procedure Spanisch;
  procedure Französisch;
  procedure Polnisch;
  procedure Russisch;
  procedure Türkisch;
  procedure Griechisch;
  procedure Chinesisch;
  procedure Hebräisch;
  procedure Arabisch;


implementation

uses
  Unit1, Unit2;

procedure Englisch;
begin
  Form1.Caption := 'nfo Editor';
  Form1.N3.Caption := '?';
  Form1.File1.Caption := 'File';
  Form1.Open1.Caption := 'Open';
  Form1.New1.Caption := 'New';
  Form1.Save1.Caption := 'Save';
  Form1.UnicodeExport1.Caption := 'Unicode';
  Form1.ExportBitmap1.Caption := 'Export Bitmap..';
  Form1.Print1.Caption := 'Print';
  Form1.Exit1.Caption := 'Exit';
  Form1.View1.Caption := 'View';
  Form1.Edit1.Caption := 'Edit';
  Form1.Copier1.Caption := 'Copy';
  Form1.Coller1.Caption := 'Paste';
  Form1.Couper1.Caption := 'Cut';
  Form1.Delete1.Caption := 'Delete';
  Form1.SelectAll1.Caption := 'Select all';
  Form1.Insert1.Caption := 'Text Overwrite';
  Form1.CharacterLimit1.Caption := 'Character Limit';
  Form1.Default3.Caption := 'Default';
  Form1.imeDate1.Caption := 'Time & Date';
  Form1.Search1.Caption := 'Search';
  Form1.Find1.Caption := 'Find..';
  Form1.Replace1.Caption := 'Replace..';
  Form1.Replaceall1.Caption := 'Replace Multi Characters...';
  Form1.Settings1.Caption := 'Settings';
  Form1.Police1.Caption := 'Font..';
  Form1.BackColor1.Caption := 'Background Color';
  Form1.Forecolor1.Caption := 'Text Color';
  Form1.extmargin1.Caption := 'Text margin (20x20)';
  Form1.ShowLogos1.Caption := 'Show Logo';
  Form1.Sign1.Caption := 'Chars';
  Form1.LowerCase1.Caption := 'Lower Case';
  Form1.Normal1.Caption := 'Normal';
  Form1.UpperCase1.Caption := 'Upper Case';
  Form1.SizeBar1.Caption := 'Size Bar';
  Form1.StatusBar2.Caption := 'Status Bar';
  Form1.SaveMynfo1.Caption := 'Save Mynfo';
  Form1.ools1.Caption := 'Tools';
  Form1.Notepad1.Caption := 'Notepad';
  Form1.Charmap1.Caption := 'Charmap';
  Form1.About1.Caption := 'About';
  Form1.Language1.Caption := 'Language';

  Form2.Caption := 'Replace Multi Characters';
  Form2.GroupBox1.Caption := ' Characters ';
  Form2.Label1.Caption := 'Replace Char';
  Form2.Label2.Caption := 'Replaced characters';
  Form2.Button4.Caption := 'Undo';
  Form2.Button3.Caption := 'Abort';
  Form2.Button1.Caption := 'Replace';
  Form2.Button2.Caption := 'Ok';
end;

procedure Deutsch;
begin
  Form1.Caption := 'nfo Editor';
  Form1.N3.Caption := '?';
  Form1.File1.Caption := 'Datei';
  Form1.Open1.Caption := 'Öffnen';
  Form1.New1.Caption := 'Neu';
  Form1.Save1.Caption := 'Speichern';
  Form1.UnicodeExport1.Caption := 'Unicode';
  Form1.ExportBitmap1.Caption := 'Exportiere Bitmap..';
  Form1.Print1.Caption := 'Drucken';
  Form1.Exit1.Caption := 'Ende';
  Form1.View1.Caption := 'Ansicht';
  Form1.Edit1.Caption := 'Bearbeiten';
  Form1.Copier1.Caption := 'Kopieren';
  Form1.Coller1.Caption := 'Einfügen';
  Form1.Couper1.Caption := 'Ausschneiden';
  Form1.Delete1.Caption := 'Löschen';
  Form1.SelectAll1.Caption := 'Alle Markieren';
  Form1.Insert1.Caption := 'Text Überschreiben';
  Form1.CharacterLimit1.Caption := 'Zeilen Begrenzung';
  Form1.Default3.Caption := 'Standard';
  Form1.imeDate1.Caption := 'Zeit & Datum';
  Form1.Search1.Caption := 'Suchen';
  Form1.Find1.Caption := 'Finden..';
  Form1.Replace1.Caption := 'Ersetzten..';
  Form1.Replaceall1.Caption := 'Ersetzte alle Zeichen..';
  Form1.Settings1.Caption := 'Einstellungen';
  Form1.Police1.Caption := 'Schrift..';
  Form1.BackColor1.Caption := 'Hintergrund Farbe';
  Form1.Forecolor1.Caption := 'Schrift Farbe';
  Form1.extmargin1.Caption := 'Text abstand (20x20)';
  Form1.ShowLogos1.Caption := 'Logo Anzeigen';
  Form1.Sign1.Caption := 'Zeichen';
  Form1.LowerCase1.Caption := 'Kleinschrift';
  Form1.Normal1.Caption := 'Normal';
  Form1.UpperCase1.Caption := 'Großschrift';
  Form1.SizeBar1.Caption := 'Schriftgrößen Einstellung';
  Form1.StatusBar2.Caption := 'Status Panel';
  Form1.SaveMynfo1.Caption := 'Speichere Mynfo';
  Form1.ools1.Caption := 'Werkzeuge';
  Form1.Notepad1.Caption := 'Texteditor';
  Form1.Charmap1.Caption := 'Zeichen Mappe';
  Form1.About1.Caption := 'Über';
  Form1.Language1.Caption := 'Sprache';

  Form2.Caption := 'Ersetzte alle Zeichen';
  Form2.GroupBox1.Caption := ' Zeichen ';
  Form2.Label1.Caption := 'Ersetzten Zeichen';
  Form2.Label2.Caption := 'Ersetzte Zeichen';
  Form2.Button4.Caption := 'Rückgängig';
  Form2.Button3.Caption := 'Abbruch';
  Form2.Button1.Caption := 'Ersetzten';
  Form2.Button2.Caption := 'Ok';
end;

procedure Italiano;
begin
  Form1.Caption := 'nfo Redattore';
  Form1.N3.Caption := '?';
  Form1.File1.Caption := 'File';
  Form1.Open1.Caption := 'Aprire';
  Form1.New1.Caption := 'Nuovo';
  Form1.Save1.Caption := 'Salva';
  Form1.UnicodeExport1.Caption := 'Unicode';
  Form1.ExportBitmap1.Caption := 'Esporta bitmap..';
  Form1.Print1.Caption := 'Stampa';
  Form1.Exit1.Caption := 'Uscita';
  Form1.View1.Caption := 'Visualizzazione';
  Form1.Edit1.Caption := 'Modificare';
  Form1.Copier1.Caption := 'Copia';
  Form1.Coller1.Caption := 'Impasto';
  Form1.Couper1.Caption := 'Taglio';
  Form1.Delete1.Caption := 'Eliminare';
  Form1.SelectAll1.Caption := 'Seleziona tutto';
  Form1.Insert1.Caption := 'Sovrascrittura del testo';
  Form1.CharacterLimit1.Caption := 'Limite di caratteri';
  Form1.Default3.Caption := 'Predefinito';
  Form1.imeDate1.Caption := 'Ora e data';
  Form1.Search1.Caption := 'Ricerca';
  Form1.Find1.Caption := 'Trovare..';
  Form1.Replace1.Caption := 'Sostituire..';
  Form1.Replaceall1.Caption := 'Sostituisci più caratteri...';
  Form1.Settings1.Caption := 'Impostazioni';
  Form1.Police1.Caption := 'Font..';
  Form1.BackColor1.Caption := 'Colore di sfondo';
  Form1.Forecolor1.Caption := 'Colore del testo';
  Form1.extmargin1.Caption := 'Margine del testo (20x20)';
  Form1.ShowLogos1.Caption := 'Mostra logo';
  Form1.Sign1.Caption := 'Caratteri';
  Form1.LowerCase1.Caption := 'Minuscolo';
  Form1.Normal1.Caption := 'Normale';
  Form1.UpperCase1.Caption := 'Maiuscolo';
  Form1.SizeBar1.Caption := 'Barra delle dimensioni';
  Form1.StatusBar2.Caption := 'Barra di stato';
  Form1.SaveMynfo1.Caption := 'Salva Mynfo';
  Form1.ools1.Caption := 'Utensili';
  Form1.Notepad1.Caption := 'Blocco note';
  Form1.Charmap1.Caption := 'Mappa caratteri';
  Form1.About1.Caption := 'Di';
  Form1.Language1.Caption := 'Lingua';

  Form2.Caption := 'Sostituisci più caratteri';
  Form2.GroupBox1.Caption := ' Caratteri ';
  Form2.Label1.Caption := 'Sostituisci carattere';
  Form2.Label2.Caption := 'Caratteri sostituiti';
  Form2.Button4.Caption := 'Disfare';
  Form2.Button3.Caption := 'Interrompi';
  Form2.Button1.Caption := 'Sostituire';
  Form2.Button2.Caption := 'Ok';
end;

procedure Spanisch;
begin
  Form1.Caption := 'nfo Editora';
  Form1.N3.Caption := '¿';
  Form1.File1.Caption := 'Archivo';
  Form1.Open1.Caption := 'Abierto';
  Form1.New1.Caption := 'Nuevo';
  Form1.Save1.Caption := 'Ahorrar';
  Form1.UnicodeExport1.Caption := 'Unicódigo';
  Form1.ExportBitmap1.Caption := 'Exportar Bitmap..';
  Form1.Print1.Caption := 'Imprimir';
  Form1.Exit1.Caption := 'Salida';
  Form1.View1.Caption := 'Vista';
  Form1.Edit1.Caption := 'Editar';
  Form1.Copier1.Caption := 'Copiar';
  Form1.Coller1.Caption := 'Pasta';
  Form1.Couper1.Caption := 'Cortar';
  Form1.Delete1.Caption := 'Borrar';
  Form1.SelectAll1.Caption := 'Seleccionar todo';
  Form1.Insert1.Caption := 'Sobrescritura de texto';
  Form1.CharacterLimit1.Caption := 'Límite de caracteres';
  Form1.Default3.Caption := 'Por defecto';
  Form1.imeDate1.Caption := 'Hora y fecha';
  Form1.Search1.Caption := 'Buscar';
  Form1.Find1.Caption := 'Encontrar..';
  Form1.Replace1.Caption := 'Reemplazar..';
  Form1.Replaceall1.Caption := 'Reemplazar múltiples caracteres...';
  Form1.Settings1.Caption := 'Ajustes';
  Form1.Police1.Caption := 'Fuente..';
  Form1.BackColor1.Caption := 'Color de fondo';
  Form1.Forecolor1.Caption := 'Color del texto';
  Form1.extmargin1.Caption := 'Margen de texto (20x20)';
  Form1.ShowLogos1.Caption := 'Mostrar logotipo';
  Form1.Sign1.Caption := 'Caracteres';
  Form1.LowerCase1.Caption := 'Minúscula';
  Form1.Normal1.Caption := 'Normal';
  Form1.UpperCase1.Caption := 'Mayúsculas';
  Form1.SizeBar1.Caption := 'Barra de tallas';
  Form1.StatusBar2.Caption := 'Barra de estado';
  Form1.SaveMynfo1.Caption := 'Guardar en Mynfo';
  Form1.ools1.Caption := 'Herramientas';
  Form1.Notepad1.Caption := 'Bloc';
  Form1.Charmap1.Caption := 'Mapa de caracteres';
  Form1.About1.Caption := 'Acerca de';
  Form1.Language1.Caption := 'Idioma';

  Form2.Caption := 'Reemplazar múltiples caracteres';
  Form2.GroupBox1.Caption := ' Personajes ';
  Form2.Label1.Caption := 'Reemplazar carácter';
  Form2.Label2.Caption := 'Caracteres reemplazados';
  Form2.Button4.Caption := 'Deshacer';
  Form2.Button3.Caption := 'Abortar';
  Form2.Button1.Caption := 'Reemplazar';
  Form2.Button2.Caption := 'Ok';
end;

procedure Französisch;
begin
  Form1.Caption := 'nfo Éditeur';
  Form1.N3.Caption := '?';
  Form1.File1.Caption := 'Déposer';
  Form1.Open1.Caption := 'Ouvrir';
  Form1.New1.Caption := 'Nouveau';
  Form1.Save1.Caption := 'Sauvegarder';
  Form1.UnicodeExport1.Caption := 'Unicode';
  Form1.ExportBitmap1.Caption := 'Exporter Bitmap..';
  Form1.Print1.Caption := 'Imprimer';
  Form1.Exit1.Caption := 'Sortie';
  Form1.View1.Caption := 'Voir';
  Form1.Edit1.Caption := 'Modifier';
  Form1.Copier1.Caption := 'Copie';
  Form1.Coller1.Caption := 'Coller';
  Form1.Couper1.Caption := 'Couper';
  Form1.Delete1.Caption := 'Supprimer';
  Form1.SelectAll1.Caption := 'Tout sélectionner';
  Form1.Insert1.Caption := 'Remplacement de texte';
  Form1.CharacterLimit1.Caption := 'Limite de caractères';
  Form1.Default3.Caption := 'Défaut';
  Form1.imeDate1.Caption := 'Heure et date';
  Form1.Search1.Caption := 'Recherche';
  Form1.Find1.Caption := 'Trouver..';
  Form1.Replace1.Caption := 'Remplacer..';
  Form1.Replaceall1.Caption := 'Remplacer plusieurs caractères...';
  Form1.Settings1.Caption := 'Paramètres';
  Form1.Police1.Caption := 'Fonte..';
  Form1.BackColor1.Caption := 'Couleur d`arrière-plan';
  Form1.Forecolor1.Caption := 'Couleur du texte';
  Form1.extmargin1.Caption := 'Marge de texte (20x20)';
  Form1.ShowLogos1.Caption := 'Afficher le logo';
  Form1.Sign1.Caption := 'Caractères';
  Form1.LowerCase1.Caption := 'Minuscules';
  Form1.Normal1.Caption := 'Normale';
  Form1.UpperCase1.Caption := 'Haut de casse';
  Form1.SizeBar1.Caption := 'Barre de taille';
  Form1.StatusBar2.Caption := 'Barre d`état';
  Form1.SaveMynfo1.Caption := 'Enregistrer Mynfo';
  Form1.ools1.Caption := 'Outils';
  Form1.Notepad1.Caption := 'Bloc-notes';
  Form1.Charmap1.Caption := 'Table de caractères';
  Form1.About1.Caption := 'À propos';
  Form1.Language1.Caption := 'Langue';

  Form2.Caption := 'Remplacer plusieurs caractères';
  Form2.GroupBox1.Caption := ' Personnages ';
  Form2.Label1.Caption := 'Remplacer le caractère';
  Form2.Label2.Caption := 'Caractères remplacés';
  Form2.Button4.Caption := 'Défaire';
  Form2.Button3.Caption := 'Avorter';
  Form2.Button1.Caption := 'Remplacer';
  Form2.Button2.Caption := 'Ok';
end;

procedure Polnisch;
begin
  Form1.Caption := 'nfo Redaktor';
  Form1.N3.Caption := 'Czy wiesz, że...?';
  Form1.File1.Caption := 'Plik';
  Form1.Open1.Caption := 'Otwarte';
  Form1.New1.Caption := 'Nowy';
  Form1.Save1.Caption := 'Ratować';
  Form1.UnicodeExport1.Caption := 'Unikod';
  Form1.ExportBitmap1.Caption := 'Eksport Bitmap..';
  Form1.Print1.Caption := 'Wydrukować';
  Form1.Exit1.Caption := 'Wyjście';
  Form1.View1.Caption := 'Pogląd';
  Form1.Edit1.Caption := 'Redagować';
  Form1.Copier1.Caption := 'Kopia';
  Form1.Coller1.Caption := 'Pasta';
  Form1.Couper1.Caption := 'Cięcie';
  Form1.Delete1.Caption := 'Usuwać';
  Form1.SelectAll1.Caption := 'Zaznacz wszystko';
  Form1.Insert1.Caption := 'Nadpisanie tekstu';
  Form1.CharacterLimit1.Caption := 'Limit znaków';
  Form1.Default3.Caption := 'Domyślny';
  Form1.imeDate1.Caption := 'Data i godzina';
  Form1.Search1.Caption := 'Szukaj';
  Form1.Find1.Caption := 'Znajdować..';
  Form1.Replace1.Caption := 'Zastępować..';
  Form1.Replaceall1.Caption := 'Zamień wiele znaków...';
  Form1.Settings1.Caption := 'Ustawienia';
  Form1.Police1.Caption := 'Chrzcielnica..';
  Form1.BackColor1.Caption := 'Kolor tła';
  Form1.Forecolor1.Caption := 'Kolor tekstu';
  Form1.extmargin1.Caption := 'Margines tekstu (20x20)';
  Form1.ShowLogos1.Caption := 'Pokaż logo';
  Form1.Sign1.Caption := 'Znaki';
  Form1.LowerCase1.Caption := 'Małe litery';
  Form1.Normal1.Caption := 'Normalna';
  Form1.UpperCase1.Caption := 'Wielkie litery';
  Form1.SizeBar1.Caption := 'Pasek rozmiaru';
  Form1.StatusBar2.Caption := 'Pasek stanu';
  Form1.SaveMynfo1.Caption := 'Zapisz Mynfo';
  Form1.ools1.Caption := 'Narzędzia';
  Form1.Notepad1.Caption := 'Notatnik';
  Form1.Charmap1.Caption := 'Tablica znaków';
  Form1.About1.Caption := 'O';
  Form1.Language1.Caption := 'Język';

  Form2.Caption := 'Zamień wiele znaków';
  Form2.GroupBox1.Caption := ' Pismo ';
  Form2.Label1.Caption := 'Zamień znak';
  Form2.Label2.Caption := 'Zastąpione znaki';
  Form2.Button4.Caption := 'Anulować';
  Form2.Button3.Caption := 'Poronić';
  Form2.Button1.Caption := 'Zastępować';
  Form2.Button2.Caption := 'Ok';
end;

procedure Russisch;
begin
  Form1.Caption := 'nfo-редактор';
  Form1.N3.Caption := '?';
  Form1.File1.Caption := 'Файл';
  Form1.Open1.Caption := 'Открыть';
  Form1.New1.Caption := 'Новый';
  Form1.Save1.Caption := 'Сохранять';
  Form1.UnicodeExport1.Caption := 'Юникод';
  Form1.ExportBitmap1.Caption := 'Экспорт растрового изображения..';
  Form1.Print1.Caption := 'Печать';
  Form1.Exit1.Caption := 'Выход';
  Form1.View1.Caption := 'Вид';
  Form1.Edit1.Caption := 'Редактировать';
  Form1.Copier1.Caption := 'Копировать';
  Form1.Coller1.Caption := 'Вставить';
  Form1.Couper1.Caption := 'Резать';
  Form1.Delete1.Caption := 'Удалить';
  Form1.SelectAll1.Caption := 'Выбрать всё';
  Form1.Insert1.Caption := 'Перезапись текста';
  Form1.CharacterLimit1.Caption := 'Ограничение по количеству символов';
  Form1.Default3.Caption := 'По умолчанию';
  Form1.imeDate1.Caption := 'Время и дата';
  Form1.Search1.Caption := 'Поиск';
  Form1.Find1.Caption := 'Находить..';
  Form1.Replace1.Caption := 'Заменять..';
  Form1.Replaceall1.Caption := 'Заменить несколько символов...';
  Form1.Settings1.Caption := 'Настройки';
  Form1.Police1.Caption := 'Шрифт..';
  Form1.BackColor1.Caption := 'Цвет фона';
  Form1.Forecolor1.Caption := 'Цвет текста';
  Form1.extmargin1.Caption := 'Отступ текста (20x20)';
  Form1.ShowLogos1.Caption := 'Показать логотип';
  Form1.Sign1.Caption := 'Символы';
  Form1.LowerCase1.Caption := 'Нижний регистр';
  Form1.Normal1.Caption := 'Нормальный';
  Form1.UpperCase1.Caption := 'Верхний регистр';
  Form1.SizeBar1.Caption := 'Панель размера';
  Form1.StatusBar2.Caption := 'Строка состояния';
  Form1.SaveMynfo1.Caption := 'Сохранить Mynfo';
  Form1.ools1.Caption := 'Инструменты';
  Form1.Notepad1.Caption := 'Блокнот';
  Form1.Charmap1.Caption := 'Таблица символов';
  Form1.About1.Caption := 'О';
  Form1.Language1.Caption := 'Язык';

  Form2.Caption := 'Заменить несколько символов';
  Form2.GroupBox1.Caption := ' Персонажи ';
  Form2.Label1.Caption := 'Заменить символ';
  Form2.Label2.Caption := 'Замененные символы';
  Form2.Button4.Caption := 'Отменить';
  Form2.Button3.Caption := 'Отмена';
  Form2.Button1.Caption := 'Заменять';
  Form2.Button2.Caption := 'Хорошо';
end;

procedure Türkisch;
begin
  Form1.Caption := 'nfo Editör';
  Form1.N3.Caption := '?';
  Form1.File1.Caption := 'Dosya';
  Form1.Open1.Caption := 'Açık';
  Form1.New1.Caption := 'Yeni';
  Form1.Save1.Caption := 'Kaydetmek';
  Form1.UnicodeExport1.Caption := 'Unicode';
  Form1.ExportBitmap1.Caption := 'Bitmap`i Dışa Aktar..';
  Form1.Print1.Caption := 'Yazdır';
  Form1.Exit1.Caption := 'Çıkış';
  Form1.View1.Caption := 'Görüş';
  Form1.Edit1.Caption := 'Düzenlemek';
  Form1.Copier1.Caption := 'Kopyala';
  Form1.Coller1.Caption := 'Yapıştır';
  Form1.Couper1.Caption := 'Kesmek';
  Form1.Delete1.Caption := 'Silmek';
  Form1.SelectAll1.Caption := 'Tümünü seç';
  Form1.Insert1.Caption := 'Metin Üzerine Yazma';
  Form1.CharacterLimit1.Caption := 'Karakter Sınırı';
  Form1.Default3.Caption := 'Varsayılan';
  Form1.imeDate1.Caption := 'Saat ve Tarih';
  Form1.Search1.Caption := 'Aramak';
  Form1.Find1.Caption := 'Bulmak..';
  Form1.Replace1.Caption := 'Yer değiştirmek..';
  Form1.Replaceall1.Caption := 'Birden Fazla Karakteri Değiştir...';
  Form1.Settings1.Caption := 'Ayarlar';
  Form1.Police1.Caption := 'Yazı Tipi..';
  Form1.BackColor1.Caption := 'Arka Plan Rengi';
  Form1.Forecolor1.Caption := 'Metin Rengi';
  Form1.extmargin1.Caption := 'Metin kenar boşluğu (20x20)';
  Form1.ShowLogos1.Caption := 'Logoyu Göster';
  Form1.Sign1.Caption := 'Karakterler';
  Form1.LowerCase1.Caption := 'Küçük harf';
  Form1.Normal1.Caption := 'Normal';
  Form1.UpperCase1.Caption := 'Büyük Harf';
  Form1.SizeBar1.Caption := 'Boyut Çubuğu';
  Form1.StatusBar2.Caption := 'Durum Çubuğu';
  Form1.SaveMynfo1.Caption := 'Mynfo`yu Kaydet';
  Form1.ools1.Caption := 'Aletler';
  Form1.Notepad1.Caption := 'Not Defteri';
  Form1.Charmap1.Caption := 'Karakter Eşlem';
  Form1.About1.Caption := 'Hakkında';
  Form1.Language1.Caption := 'Dil';

  Form2.Caption := 'Birden Fazla Karakteri Değiştir';
  Form2.GroupBox1.Caption := ' Karakterler ';
  Form2.Label1.Caption := 'Karakteri Değiştir';
  Form2.Label2.Caption := 'Değiştirilen karakterler';
  Form2.Button4.Caption := 'Geri Al';
  Form2.Button3.Caption := 'İptal Et';
  Form2.Button1.Caption := 'Yer değiştirmek';
  Form2.Button2.Caption := 'Tamam';
end;

procedure Griechisch;
begin
  Form1.Caption := 'nfo Συντάκτης';
  Form1.N3.Caption := '?';
  Form1.File1.Caption := 'Αρχείο';
  Form1.Open1.Caption := 'Ανοιχτό';
  Form1.New1.Caption := 'Νέος';
  Form1.Save1.Caption := 'Εκτός';
  Form1.UnicodeExport1.Caption := 'Unicode';
  Form1.ExportBitmap1.Caption := 'Εξαγωγή Bitmap..';
  Form1.Print1.Caption := 'Αποτύπωμα';
  Form1.Exit1.Caption := 'Εξοδος';
  Form1.View1.Caption := 'Θέα';
  Form1.Edit1.Caption := 'Εκδίδω';
  Form1.Copier1.Caption := 'Αντίγραφο';
  Form1.Coller1.Caption := 'Πάστα';
  Form1.Couper1.Caption := 'Τομή';
  Form1.Delete1.Caption := 'Διαγράφω';
  Form1.SelectAll1.Caption := 'Επιλέξτε όλα';
  Form1.Insert1.Caption := 'Αντικατάσταση κειμένου';
  Form1.CharacterLimit1.Caption := 'Όριο χαρακτήρων';
  Form1.Default3.Caption := 'Αθέτηση';
  Form1.imeDate1.Caption := 'Ώρα & Ημερομηνία';
  Form1.Search1.Caption := 'Ερευνα';
  Form1.Find1.Caption := 'Εύρημα..';
  Form1.Replace1.Caption := 'Αντικαθιστώ..';
  Form1.Replaceall1.Caption := 'Αντικατάσταση πολλών χαρακτήρων...';
  Form1.Settings1.Caption := 'Ρυθμίσεις';
  Form1.Police1.Caption := 'Γραμματοσειρά..';
  Form1.BackColor1.Caption := 'Χρώμα φόντου';
  Form1.Forecolor1.Caption := 'Χρώμα κειμένου';
  Form1.extmargin1.Caption := 'Περιθώριο κειμένου (20x20)';
  Form1.ShowLogos1.Caption := 'Εμφάνιση λογότυπου';
  Form1.Sign1.Caption := 'Οστεοφυλάκιο';
  Form1.LowerCase1.Caption := 'Μικρά γράμματα';
  Form1.Normal1.Caption := 'Κανονικός';
  Form1.UpperCase1.Caption := 'Κεφάλαιο';
  Form1.SizeBar1.Caption := 'Μπάρα μεγέθους';
  Form1.StatusBar2.Caption := 'Γραμμή κατάστασης';
  Form1.SaveMynfo1.Caption := 'Αποθήκευση Mynfo';
  Form1.ools1.Caption := 'Εργαλεία';
  Form1.Notepad1.Caption := 'Μπλοκ';
  Form1.Charmap1.Caption := 'Charmap';
  Form1.About1.Caption := 'Για';
  Form1.Language1.Caption := 'Γλώσσα';

  Form2.Caption := 'Αντικατάσταση πολλών χαρακτήρων';
  Form2.GroupBox1.Caption := ' Χαρακτήρες ';
  Form2.Label1.Caption := 'Αντικαταστήστε τον Χαρ';
  Form2.Label2.Caption := 'Αντικαταστάθηκαν χαρακτήρες';
  Form2.Button4.Caption := 'Ξεκάνω';
  Form2.Button3.Caption := 'Αμβλώνω';
  Form2.Button1.Caption := 'Αντικαθιστώ';
  Form2.Button2.Caption := 'Εντάξει';
end;

procedure Chinesisch;
begin
  Form1.Caption := 'nfo 編輯';
  Form1.N3.Caption := '?';
  Form1.File1.Caption := '文件';
  Form1.Open1.Caption := '打開';
  Form1.New1.Caption := '新的';
  Form1.Save1.Caption := '節省';
  Form1.UnicodeExport1.Caption := '統一碼';
  Form1.ExportBitmap1.Caption := '匯出點陣圖..';
  Form1.Print1.Caption := '列印';
  Form1.Exit1.Caption := '出口';
  Form1.View1.Caption := '看法';
  Form1.Edit1.Caption := '編輯';
  Form1.Copier1.Caption := '複製';
  Form1.Coller1.Caption := '貼上';
  Form1.Couper1.Caption := '切';
  Form1.Delete1.Caption := '刪除';
  Form1.SelectAll1.Caption := '全選';
  Form1.Insert1.Caption := '文字覆蓋';
  Form1.CharacterLimit1.Caption := '字元限制';
  Form1.Default3.Caption := '預設';
  Form1.imeDate1.Caption := '時間和日期';
  Form1.Search1.Caption := '搜尋';
  Form1.Find1.Caption := '尋找..';
  Form1.Replace1.Caption := '代替..';
  Form1.Replaceall1.Caption := '替換多個字符...';
  Form1.Settings1.Caption := '設定';
  Form1.Police1.Caption := '字體..';
  Form1.BackColor1.Caption := '背景顏色';
  Form1.Forecolor1.Caption := '文字顏色';
  Form1.extmargin1.Caption := '文字頁邊距 (20x20)';
  Form1.ShowLogos1.Caption := '顯示標誌';
  Form1.Sign1.Caption := '人物';
  Form1.LowerCase1.Caption := '小寫';
  Form1.Normal1.Caption := '普通的';
  Form1.UpperCase1.Caption := '大寫';
  Form1.SizeBar1.Caption := '尺寸欄';
  Form1.StatusBar2.Caption := '狀態列';
  Form1.SaveMynfo1.Caption := '儲存我的信息';
  Form1.ools1.Caption := '工具';
  Form1.Notepad1.Caption := '記事本';
  Form1.Charmap1.Caption := '字元映射表';
  Form1.About1.Caption := '關於';
  Form1.Language1.Caption := '語言';

  Form2.Caption := '替換多個字符';
  Form2.GroupBox1.Caption := ' 人物 ';
  Form2.Label1.Caption := '替換字元';
  Form2.Label2.Caption := '已替換字符';
  Form2.Button4.Caption := '撤銷';
  Form2.Button3.Caption := '流產';
  Form2.Button1.Caption := '代替';
  Form2.Button2.Caption := '好的';
end;

procedure Hebräisch;
begin
  Form1.Caption := 'nfo עוֹרֵך';
  Form1.N3.Caption := '?';
  Form1.File1.Caption := 'קוֹבֶץ';
  Form1.Open1.Caption := 'לִפְתוֹחַ';
  Form1.New1.Caption := 'חָדָשׁ';
  Form1.Save1.Caption := 'לְהַצִיל';
  Form1.UnicodeExport1.Caption := 'Unicode';
  Form1.ExportBitmap1.Caption := 'ייצוא מפת סיביות..';
  Form1.Print1.Caption := 'הֶדפֵּס';
  Form1.Exit1.Caption := 'יְצִיאָה';
  Form1.View1.Caption := 'נוֹף';
  Form1.Edit1.Caption := 'לַעֲרוֹך';
  Form1.Copier1.Caption := 'לְהַעְתִיק';
  Form1.Coller1.Caption := 'לְהַדבִּיק';
  Form1.Couper1.Caption := 'גְזִירָה';
  Form1.Delete1.Caption := 'לִמְחוֹק';
  Form1.SelectAll1.Caption := 'בחר הכל';
  Form1.Insert1.Caption := 'החלפת טקסט';
  Form1.CharacterLimit1.Caption := 'מגבלת אופי';
  Form1.Default3.Caption := 'בְּרִירַת מֶחדָל';
  Form1.imeDate1.Caption := 'זמן ותאריך';
  Form1.Search1.Caption := 'לְחַפֵּשׂ';
  Form1.Find1.Caption := 'לִמצוֹא..';
  Form1.Replace1.Caption := 'לְהַחלִיף..';
  Form1.Replaceall1.Caption := 'החלפת תווים מרובים...';
  Form1.Settings1.Caption := 'הגדרות';
  Form1.Police1.Caption := 'גוֹפָן..';
  Form1.BackColor1.Caption := 'צבע רקע';
  Form1.Forecolor1.Caption := 'צבע טקסט';
  Form1.extmargin1.Caption := 'שוליים לטקסט (20x20)';
  Form1.ShowLogos1.Caption := 'הצג לוגו';
  Form1.Sign1.Caption := 'תווים';
  Form1.LowerCase1.Caption := 'אוֹתִיוֹת קְטָנוֹת';
  Form1.Normal1.Caption := 'נוֹרמָלִי';
  Form1.UpperCase1.Caption := 'אוֹתִיוֹת גְדוֹלוֹת';
  Form1.SizeBar1.Caption := 'סרגל מידות';
  Form1.StatusBar2.Caption := 'שורת המצב';
  Form1.SaveMynfo1.Caption := 'שמור את Mynfo';
  Form1.ools1.Caption := 'כְּלֵי עֲבוֹדָה';
  Form1.Notepad1.Caption := 'פנקס רשימות';
  Form1.Charmap1.Caption := 'צארמאפ';
  Form1.About1.Caption := 'אוֹדוֹת';
  Form1.Language1.Caption := 'שָׂפָה';

  Form2.Caption := 'החלף ריבוי תווים';
  Form2.GroupBox1.Caption := ' דמויות ';
  Form2.Label1.Caption := 'החלף Char';
  Form2.Label2.Caption := 'תווים שהוחלפו';
  Form2.Button4.Caption := 'לְבַטֵל';
  Form2.Button3.Caption := 'לְהַפִּיל';
  Form2.Button1.Caption := 'לְהַחלִיף';
  Form2.Button2.Caption := 'בְּסֵדֶר';
end;

procedure Arabisch;
begin
  Form1.Caption := 'محرر المعلومات';
  Form1.N3.Caption := 'هل لديك سؤال؟';
  Form1.File1.Caption := 'ملف';
  Form1.Open1.Caption := 'يفتح';
  Form1.New1.Caption := 'جديد';
  Form1.Save1.Caption := 'يحفظ';
  Form1.UnicodeExport1.Caption := 'يونيكود';
  Form1.ExportBitmap1.Caption := 'تصدير صورة نقطية..';
  Form1.Print1.Caption := 'مطبعة';
  Form1.Exit1.Caption := 'مخرج';
  Form1.View1.Caption := 'منظر';
  Form1.Edit1.Caption := 'يحرر';
  Form1.Copier1.Caption := 'ينسخ';
  Form1.Coller1.Caption := 'لصق';
  Form1.Couper1.Caption := 'يقطع';
  Form1.Delete1.Caption := 'يمسح';
  Form1.SelectAll1.Caption := 'تحديد الكل';
  Form1.Insert1.Caption := 'استبدال النص';
  Form1.CharacterLimit1.Caption := 'الحد الأقصى لعدد الأحرف';
  Form1.Default3.Caption := 'تقصير';
  Form1.imeDate1.Caption := 'الوقت والتاريخ';
  Form1.Search1.Caption := 'يبحث';
  Form1.Find1.Caption := 'يجد..';
  Form1.Replace1.Caption := 'يستبدل..';
  Form1.Replaceall1.Caption := 'استبدال أحرف متعددة...';
  Form1.Settings1.Caption := 'إعدادات';
  Form1.Police1.Caption := 'الخط..';
  Form1.BackColor1.Caption := 'لون الخلفية';
  Form1.Forecolor1.Caption := 'لون النص';
  Form1.extmargin1.Caption := 'هامش النص (20×20)';
  Form1.ShowLogos1.Caption := 'عرض الشعار';
  Form1.Sign1.Caption := 'رموز';
  Form1.LowerCase1.Caption := 'أحرف صغيرة';
  Form1.Normal1.Caption := 'طبيعي';
  Form1.UpperCase1.Caption := 'أحرف كبيرة';
  Form1.SizeBar1.Caption := 'شريط الحجم';
  Form1.StatusBar2.Caption := 'شريط الحالة';
  Form1.SaveMynfo1.Caption := 'حفظ Mynfo';
  Form1.ools1.Caption := 'أدوات';
  Form1.Notepad1.Caption := 'المفكرة';
  Form1.Charmap1.Caption := 'خريطة الأحرف';
  Form1.About1.Caption := 'عن';
  Form1.Language1.Caption := 'لغة';

  Form2.Caption := 'استبدال أحرف متعددة';
  Form2.GroupBox1.Caption := ' الشخصيات ';
  Form2.Label1.Caption := 'استبدال حرف';
  Form2.Label2.Caption := 'الرموز المستبدلة';
  Form2.Button4.Caption := 'تراجع';
  Form2.Button3.Caption := 'إلغاء';
  Form2.Button1.Caption := 'يستبدل';
  Form2.Button2.Caption := 'نعم';
end;

end.